version: 2
jobs:
  build:
    working_directory: /go/src/github.com/assetnote/commonspeak2
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go get -u -v -t github.com/Masterminds/glide
      - run: glide install -v
      - run: go build
  release:
    working_directory: /go/src/github.com/assetnote/commonspeak2
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go get -u -v -t github.com/Masterminds/glide
      - run: glide install -v
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  build:
    jobs:
      - build
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
